# Generated by Django 4.1.2 on 2023-02-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storecornercordsdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storegpsdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storenodedata',
            options={},
        ),
    ]
